In [2]:
import numpy as np
import pandas as pd

In [9]:
bioinfo = pd.read_parquet("../data/raw/bioinfo.parquet")
bioinfo.info()

<class 'pandas.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bioguide_id     555 non-null    str
 1   Full name       555 non-null    str
 2   Chamber         555 non-null    str
 3   State           555 non-null    str
 4   Party           555 non-null    str
 5   District        439 non-null    float64
 6   birthYear       554 non-null    str
 7   image           554 non-null    str
 8   Office address  539 non-null    str
 9   Phone           539 non-null    str
 10  Website         539 non-null    str
dtypes: float64(1), str(10)
memory usage: 166.9 KB

In [10]:
bioinfo['bioguide_id'].duplicated().value_counts()

bioguide_id
False    555
Name: count, dtype: int64

In [12]:
bioinfo.head(3).T

,0,1,2
bioguide_id,R000575,S001185,P000609
Full name,Mike Rogers,Terri A. Sewell,Gary J. Palmer
Chamber,House of Representatives,House of Representatives,House of Representatives
State,Alabama,Alabama,Alabama
Party,Republican,Democratic,Republican
District,3.0,7.0,6.0
birthYear,1958,1965,1954
image,https://www.congress.gov/img/member/116_rp_al_...,https://www.congress.gov/img/member/s001185_20...,https://www.congress.gov/img/member/p000609_20...
Office address,"2469 Rayburn House Office Building, Washington...","1035 Longworth House Office Building, Washingt...","170 Cannon House Office Building, Washington, ..."
Phone,(202) 225-3261,(202) 225-2665,(202) 225-4921
Website,https://mikerogers.house.gov/,https://sewell.house.gov/,https://palmer.house.gov/

In [15]:
def pandas_df_to_dbml(df: pd.DataFrame, table_name: str) -> str:
    """
    Converts a pandas DataFrame to a DBML string.
    Args:
        df: The pandas DataFrame to convert.
        table_name: The name of the table in the DBML schema.
    Returns:
        A DBML string representing the DataFrame schema.
    """
    dbml_string = f"Table {table_name} {{\n"
    for column_name, column_type in df.dtypes.items():
        dbml_type = map_pandas_dtype_to_dbml_type(column_type)
        dbml_string += f"  {column_name} {dbml_type}\n"
    dbml_string += "}\n"
    return dbml_string
def map_pandas_dtype_to_dbml_type(dtype) -> str:
    """Maps a pandas dtype to a DBML type."""
    dtype_name = str(dtype)
    if "int" in dtype_name:
      return "int"
    if "float" in dtype_name:
      return "float"
    if "datetime" in dtype_name:
        return "datetime"
    return "varchar"

In [16]:
print(pandas_df_to_dbml(bioinfo, "members"))

Table members {
  bioguide_id varchar
  Full name varchar
  Chamber varchar
  State varchar
  Party varchar
  District float
  birthYear varchar
  image varchar
  Office address varchar
  Phone varchar
  Website varchar
}

In [17]:
bioinfo.columns = [x.replace(" ", "_").lower() for x in bioinfo.columns]
print(pandas_df_to_dbml(bioinfo, "members"))

Table members {
  bioguide_id varchar
  full_name varchar
  chamber varchar
  state varchar
  party varchar
  district float
  birthyear varchar
  image varchar
  office_address varchar
  phone varchar
  website varchar
}

In [67]:
ideology = pd.read_parquet("../data/raw/ideology.parquet")
ideology.info()

<class 'pandas.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   bioname              557 non-null    str
 1   chamber              557 non-null    str
 2   left_right_ideology  555 non-null    float64
 3   state_abbrev         557 non-null    str
 4   district_code        557 non-null    int64
 5   icpsr                557 non-null    int64
 6   bioguide_id          556 non-null    str
 7   party                557 non-null    str
 8   fec_id               538 non-null    object
dtypes: float64(1), int64(2), object(1), str(5)
memory usage: 60.7+ KB

In [68]:
ideology.head(13).T

,0,1,2,3,4,5,6,7,8,9,10,11,12
bioname,"TRUMP, Donald John","ROGERS, Mike Dennis","SEWELL, Terri","PALMER, Gary James","MOORE, Barry","STRONG, Dale","FIGURES, Shomari","ADERHOLT, Robert","BEGICH, Nicholas J., III","RADEWAGEN, Aumua Amata Coleman","GRIJALVA, Raúl M.","GOSAR, Paul","SCHWEIKERT, David"
chamber,President,House,House,House,House,House,House,House,House,House,House,House,House
left_right_ideology,0.403,0.379,-0.402,0.67,0.646,0.61,-0.411,0.405,0.59,0.327,-0.598,0.701,0.553
state_abbrev,USA,AL,AL,AL,AL,AL,AL,AL,AK,AS,AZ,AZ,AZ
district_code,0,3,7,6,1,5,2,4,1,0,7,9,1
icpsr,99912,20301,21102,21500,22140,22366,22515,29701,22503,21995,20305,21103,21105
bioguide_id,NaN,R000575,S001185,P000609,M001212,S001220,F000481,A000055,B001323,R000600,G000551,G000565,S001183
party,Republican,Republican,Democrat,Republican,Republican,Republican,Democrat,Republican,Republican,Republican,Democrat,Republican,Republican
fec_id,None,[H2AL03032],[H0AL07086],[H4AL06098],"[H8AL02171, S6AL00476]",[H2AL05102],[H4AL02170],[H6AL04098],[H2AK01083],[H4AS00036],None,[H0AZ01259],"[H4AZ06045, H8AZ05097]"

In [69]:
bioinfo.head(3).T

,0,1,2
bioguide_id,R000575,S001185,P000609
full_name,Mike Rogers,Terri A. Sewell,Gary J. Palmer
chamber,House of Representatives,House of Representatives,House of Representatives
state,Alabama,Alabama,Alabama
party,Republican,Democratic,Republican
district,3.0,7.0,6.0
birthyear,1958,1965,1954
image,https://www.congress.gov/img/member/116_rp_al_...,https://www.congress.gov/img/member/s001185_20...,https://www.congress.gov/img/member/p000609_20...
office_address,"2469 Rayburn House Office Building, Washington...","1035 Longworth House Office Building, Washingt...","170 Cannon House Office Building, Washington, ..."
phone,(202) 225-3261,(202) 225-2665,(202) 225-4921
website,https://mikerogers.house.gov/,https://sewell.house.gov/,https://palmer.house.gov/

In [70]:
ideology = ideology[['icpsr', 'bioguide_id', 'fec_id', 'left_right_ideology']]
ideology

     icpsr bioguide_id                  fec_id  left_right_ideology
0    99912         NaN                    None                0.403
1    20301     R000575             [H2AL03032]                0.379
2    21102     S001185             [H0AL07086]               -0.402
3    21500     P000609             [H4AL06098]                0.670
4    22140     M001212  [H8AL02171, S6AL00476]                0.646
..     ...         ...                     ...                  ...
552  42504     J000312             [S4WV00332]                0.562
553  29940     B001230  [H8WI00018, S2WI00219]               -0.484
554  41111     J000293             [S0WI00197]                0.648
555  20953     L000571  [H8WY00148, S0WY00137]                0.682
556  40707     B001261             [S6WY00068]                0.540

[557 rows x 4 columns]

In [71]:
fec = ideology.explode('fec_id')
fec

     icpsr bioguide_id     fec_id  left_right_ideology
0    99912         NaN        NaN                0.403
1    20301     R000575  H2AL03032                0.379
2    21102     S001185  H0AL07086               -0.402
3    21500     P000609  H4AL06098                0.670
4    22140     M001212  H8AL02171                0.646
..     ...         ...        ...                  ...
553  29940     B001230  S2WI00219               -0.484
554  41111     J000293  S0WI00197                0.648
555  20953     L000571  H8WY00148                0.682
555  20953     L000571  S0WY00137                0.682
556  40707     B001261  S6WY00068                0.540

[647 rows x 4 columns]

In [72]:
ideology = ideology.drop(['fec_id'], axis=1)
fec = fec.drop(['left_right_ideology'], axis=1)

In [73]:
fec

     icpsr bioguide_id     fec_id
0    99912         NaN        NaN
1    20301     R000575  H2AL03032
2    21102     S001185  H0AL07086
3    21500     P000609  H4AL06098
4    22140     M001212  H8AL02171
..     ...         ...        ...
553  29940     B001230  S2WI00219
554  41111     J000293  S0WI00197
555  20953     L000571  H8WY00148
555  20953     L000571  S0WY00137
556  40707     B001261  S6WY00068

[647 rows x 3 columns]

```
members = pd.merge(bioinfo, 
                   ideology,
                   how='outer',
                   #validate='one_to_one',
                   indicator='matched')
members['matched'].value_counts()

---------------------------------------------------------------------------
MergeError                                Traceback (most recent call last)
Cell In[47], line 1
----> 1 members = pd.merge(bioinfo, 
      2                    ideology,
      3                    how='outer',
      4                    validate='one_to_one',

File ~\anaconda3\envs\ds6600\Lib\site-packages\pandas\core\reshape\merge.py:385, in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
    371     return _cross_merge(
    372         left_df,
    373         right_df,
   (...)    382         validate=validate,
    383     )
    384 else:
--> 385     op = _MergeOperation(
    386         left_df,
    387         right_df,
    388         how=how,
    389         on=on,
    390         left_on=left_on,
    391         right_on=right_on,
    392         left_index=left_index,
    393         right_index=right_index,
    394         sort=sort,
...

MergeError: Merge keys are not unique in right dataset; not a one-to-one merge
Duplicates in right:
 bioguide_id
    K000401 ...
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
```

In [74]:
ideology[ideology['bioguide_id'].duplicated()]

    icpsr bioguide_id  left_right_ideology
78  92336     K000401                0.152

In [75]:
ideology.query('bioguide_id == "K000401"')

    icpsr bioguide_id  left_right_ideology
60  22336     K000401                0.253
78  92336     K000401                0.152

In [76]:
ideology = ideology.groupby(['bioguide_id']).agg({'left_right_ideology': 'mean'}).reset_index() # average the duplicate congressmen's ideology scores to handle the duplicate row

In [77]:
members = pd.merge(bioinfo, 
                   ideology,
                   how='outer',
                   validate='one_to_one',
                   indicator='matched')
members['matched'].value_counts()
members = members.drop(['matched'], axis=1)

In [78]:
members.head(3).T

,0,1,2
bioguide_id,A000055,A000148,A000369
full_name,Robert B. Aderholt,Jake Auchincloss,Mark E. Amodei
chamber,House of Representatives,House of Representatives,House of Representatives
state,Alabama,Massachusetts,Nevada
party,Republican,Democratic,Republican
district,4.0,4.0,2.0
birthyear,1965,1988,1958
image,https://www.congress.gov/img/member/a000055_20...,https://www.congress.gov/img/member/67817e391f...,https://www.congress.gov/img/member/a000369_20...
office_address,"272 Cannon House Office Building, Washington, ...","1524 Longworth House Office Building, Washingt...","104 Cannon House Office Building, Washington, ..."
phone,(202) 225-4876,(202) 225-5931,(202) 225-6155
website,https://aderholt.house.gov/,https://auchincloss.house.gov,https://amodei.house.gov
left_right_ideology,0.405,-0.272,0.384

In [79]:
print(pandas_df_to_dbml(members, 'members'))

Table members {
  bioguide_id varchar
  full_name varchar
  chamber varchar
  state varchar
  party varchar
  district float
  birthyear varchar
  image varchar
  office_address varchar
  phone varchar
  website varchar
  left_right_ideology float
}

In [80]:
print(pandas_df_to_dbml(fec, 'crosswalk'))

Table crosswalk {
  icpsr int
  bioguide_id varchar
  fec_id varchar
}

In [85]:
terms = pd.read_parquet("../data/raw/terms.parquet")
terms.info()

<class 'pandas.DataFrame'>
RangeIndex: 3267 entries, 0 to 3266
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bioguide_id  3267 non-null   str
 1   chamber      3267 non-null   str
 2   congress     3267 non-null   int64
 3   stateCode    3267 non-null   str
 4   startYear    3267 non-null   int64
 5   endYear      3267 non-null   int64
 6   district     2523 non-null   float64
dtypes: float64(1), int64(3), str(3)
memory usage: 272.4 KB

In [86]:
terms

,bioguide_id,chamber,congress,stateCode,startYear,endYear,district
0,R000575,House of Representatives,108,AL,2003,2005,3.0
1,R000575,House of Representatives,109,AL,2005,2007,3.0
2,R000575,House of Representatives,110,AL,2007,2009,3.0
3,R000575,House of Representatives,111,AL,2009,2011,3.0
4,R000575,House of Representatives,112,AL,2011,2013,3.0
...,...,...,...,...,...,...,...
3262,B001261,Senate,115,WY,2017,2019,NaN
3263,B001261,Senate,116,WY,2019,2021,NaN
3264,B001261,Senate,117,WY,2021,2023,NaN
3265,B001261,Senate,118,WY,2023,2025,NaN
3266,B001261,Senate,119,WY,2025,2027,NaN

In [87]:
# drop startyear and endyear
terms = terms.drop(['startYear', 'endYear'], axis=1)
terms.columns = [x.lower() for x in terms.columns]
print(pandas_df_to_dbml(terms, 'terms'))

Table terms {
  bioguide_id varchar
  chamber varchar
  congress int
  statecode varchar
  district float
}

In [88]:
# saving the processed dataframes to CSV files
members.to_csv("../data/processed/members.csv", index=False)
fec.to_csv("../data/processed/fec.csv", index=False)
terms.to_csv("../data/processed/terms.csv", index=False)