In [1]:
import numpy as np
import pandas as pd
import os
import requests
import json
import dotenv

In [2]:
# Bring and loading our API key into jupyter notebook without exposing it
dotenv.load_dotenv() #brings the environemtnal variables from the env file and be brought into the kernal in the jupyter notebook

True

In [3]:
congresskey = os.getenv('congresskey') #note: do not print congresskey because even if the kernel cell is delted, the output is cached. So, you will need to completely delete jupyter notebook file

There are five pieces of information you need to naviagte any API and its poor documentation:
1. How you get an API key (or another credentiial) to get access to the data (check)

2. Root: the beginning of the URl for any endpooint contained within the API

A URL: `root / endpoint ? parameters`

3. Endpoint: the middle of the URL, specifies which data store on the API to access

4. Parameters (End point parameters): ways to control what exactly is returned when you access an endpoint. There are two kinds of paramters:
    * query paramters: appear after the ?, but requests formats this for using the `params` arguement
    * path parameters: supposed to be entered as part of the endpoint itself
    
5. How to supply your API key back tot he API to prove that you are you

In [4]:
# style: I dont like putting a slash at the end of the root because the slash is usually part of the endpoint
root =  'https://api.congress.gov/v3' 

endpoint = '/member'

params = {'format': 'json', 'currentMember': 'true', 'api_key': congresskey}

In [5]:
r = requests.get(root + endpoint, params=params)
r

In [6]:
r.text

'{\n    "members": [\n        {\n            "bioguideId": "W000832",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg"\n            },\n            "district": 14,\n            "name": "Wahab, Aisha",\n            "partyName": "Democratic",\n            "state": "California",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/W000832?format=json"\n        },\n        {\n            "bioguideId": "B001328",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg"\n            },\n            "district": 13,\n            "name": "Blair, Everton",\n            "partyName": "Democratic",\n            "state": "Georgia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/B001328?format=json"\n        },\n        {\n            "bioguideId": "G000607",\n            "depiction": {\n                "imageUrl": "https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg"\n            },\n            "district": 1,\n            "name": "Gallagher, James",\n            "partyName": "Republican",\n            "state": "California",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/G000607?format=json"\n        },\n        {\n            "bioguideId": "M001246",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg"\n            },\n            "district": 11,\n            "name": "Mejia, Analilia",\n            "partyName": "Democratic",\n            "state": "New Jersey",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/M001246?format=json"\n        },\n        {\n            "bioguideId": "F000485",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg"\n            },\n            "district": 14,\n            "name": "Fuller, Clay",\n            "partyName": "Republican",\n            "state": "Georgia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/F000485?format=json"\n        },\n        {\n            "bioguideId": "M001245",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg"\n            },\n            "district": 18,\n            "name": "Menefee, Christian D.",\n            "partyName": "Democratic",\n            "state": "Texas",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/M001245?format=json"\n        },\n        {\n            "bioguideId": "V000139",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg"\n            },\n            "district": 7,\n            "name": "Van Epps, Matt",\n            "partyName": "Republican",\n            "state": "Tennessee",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/V000139?format=json"\n        },\n        {\n            "bioguideId": "P000622",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg"\n            },\n            "district": 1,\n            "name": "Patronis, Jimmy",\n            "partyName": "Republican",\n            "state": "Florida",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/P000622?format=json"\n        },\n        {\n            "bioguideId": "F000484",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg"\n            },\n            "district": 6,\n            "name": "Fine, Randy",\n            "partyName": "Republican",\n            "state": "Florida",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/F000484?format=json"\n        },\n        {\n            "bioguideId": "V000138",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg"\n            },\n            "district": 7,\n            "name": "Vindman, Eugene Simon",\n            "partyName": "Democratic",\n            "state": "Virginia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/V000138?format=json"\n        },\n        {\n            "bioguideId": "T000490",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg"\n            },\n            "district": 2,\n            "name": "Taylor, David J.",\n            "partyName": "Republican",\n            "state": "Ohio",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/T000490?format=json"\n        },\n        {\n            "bioguideId": "S001230",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg"\n            },\n            "district": 10,\n            "name": "Subramanyam, Suhas",\n            "partyName": "Democratic",\n            "state": "Virginia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/S001230?format=json"\n        },\n        {\n            "bioguideId": "S001229",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg"\n            },\n            "district": 6,\n            "name": "Shreve, Jefferson",\n            "partyName": "Republican",\n            "state": "Indiana",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/S001229?format=json"\n        },\n        {\n            "bioguideId": "S001228",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg"\n            },\n            "district": 2,\n            "name": "Schmidt, Derek",\n            "partyName": "Republican",\n            "state": "Kansas",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/S001228?format=json"\n        },\n        {\n            "bioguideId": "R000622",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg"\n            },\n            "district": 19,\n            "name": "Riley, Josh",\n            "partyName": "Democratic",\n            "state": "New York",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/R000622?format=json"\n        },\n        {\n            "bioguideId": "P000621",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg"\n            },\n            "district": 9,\n            "name": "Pou, Nellie",\n            "partyName": "Democratic",\n            "state": "New Jersey",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/P000621?format=json"\n        },\n        {\n            "bioguideId": "O000176",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg"\n            },\n            "district": 2,\n            "name": "Olszewski, Johnny",\n            "partyName": "Democratic",\n            "state": "Maryland",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/O000176?format=json"\n        },\n        {\n            "bioguideId": "M001240",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg"\n            },\n            "district": 6,\n            "name": "McDowell, Addison P.",\n            "partyName": "Republican",\n            "state": "North Carolina",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/M001240?format=json"\n        },\n        {\n            "bioguideId": "M001239",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg"\n            },\n            "district": 5,\n            "name": "McGuire, John J.",\n            "partyName": "Republican",\n            "state": "Virginia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/M001239?format=json"\n        },\n        {\n            "bioguideId": "M001238",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67744b460b34857ecc909143_200.jpg"\n            },\n            "name": "McBride, Sarah",\n            "partyName": "Democratic",\n            "state": "Delaware",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-24T07:40:27Z",\n            "url": "https://api.congress.gov/v3/member/M001238?format=json"\n        }\n    ],\n    "pagination": {\n        "count": 539,\n        "next": "https://api.congress.gov/v3/member?currentMember=true&offset=20&limit=20&format=json"\n    },\n    "request": {\n        "contentType": "application/json",\n        "format": "json"\n    }\n}'

In [7]:
r.json()

{'members': [{'bioguideId': 'W000832',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
   'district': 14,
   'name': 'Wahab, Aisha',
   'partyName': 'Democratic',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
  {'bioguideId': 'B001328',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
   'district': 13,
   'name': 'Blair, Everton',
   'partyName': 'Democratic',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
  {'bioguideId': 'G000607',
   'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
   'district': 1,
   'name': 'Gallagher, James',
   'partyName': 'Republican',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
  {'bioguideId': 'M001246',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
   'district': 11,
   'name': 'Mejia, Analilia',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
  {'bioguideId': 'F000485',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
   'district': 14,
   'name': 'Fuller, Clay',
   'partyName': 'Republican',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
  {'bioguideId': 'M001245',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
   'district': 18,
   'name': 'Menefee, Christian D.',
   'partyName': 'Democratic',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
  {'bioguideId': 'V000139',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
   'district': 7,
   'name': 'Van Epps, Matt',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
  {'bioguideId': 'P000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
   'district': 1,
   'name': 'Patronis, Jimmy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
  {'bioguideId': 'F000484',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
   'district': 6,
   'name': 'Fine, Randy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
  {'bioguideId': 'V000138',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
   'district': 7,
   'name': 'Vindman, Eugene Simon',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
  {'bioguideId': 'T000490',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
   'district': 2,
   'name': 'Taylor, David J.',
   'partyName': 'Republican',
   'state': 'Ohio',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
  {'bioguideId': 'S001230',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
   'district': 10,
   'name': 'Subramanyam, Suhas',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
  {'bioguideId': 'S001229',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
   'district': 6,
   'name': 'Shreve, Jefferson',
   'partyName': 'Republican',
   'state': 'Indiana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
  {'bioguideId': 'S001228',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
   'district': 2,
   'name': 'Schmidt, Derek',
   'partyName': 'Republican',
   'state': 'Kansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
  {'bioguideId': 'R000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
   'district': 19,
   'name': 'Riley, Josh',
   'partyName': 'Democratic',
   'state': 'New York',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
  {'bioguideId': 'P000621',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
   'district': 9,
   'name': 'Pou, Nellie',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
  {'bioguideId': 'O000176',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
   'district': 2,
   'name': 'Olszewski, Johnny',
   'partyName': 'Democratic',
   'state': 'Maryland',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
  {'bioguideId': 'M001240',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
   'district': 6,
   'name': 'McDowell, Addison P.',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001240?format=json'},
  {'bioguideId': 'M001239',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
   'district': 5,
   'name': 'McGuire, John J.',
   'partyName': 'Republican',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001239?format=json'},
  {'bioguideId': 'M001238',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744b460b34857ecc909143_200.jpg'},
   'name': 'McBride, Sarah',
   'partyName': 'Democratic',
   'state': 'Delaware',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001238?format=json'}],
 'pagination': {'count': 539,
  'next': 'https://api.congress.gov/v3/member?currentMember=true&offset=20&limit=20&format=json'},
 'request': {'contentType': 'application/json', 'format': 'json'}}

1. User-Agent strings/headers
    - A piece of text you give to the data server to tell them a bit about who you are and what your system is.
2. Navigate a JSON
3. Pagination and rate limits

### Step 1.

In [8]:
botname = 'ds6600'
version = '0.0'
purpose = 'Class demonstration'
email = 'ncq3dw@virginia.edu'
useragent = f'{botname}/{version} ({purpose}; {email}) python-requests/{requests.__version__}'
headers = {'User-Agent': useragent}
headers

{'User-Agent': 'ds6600/0.0 (Class demonstration; ncq3dw@virginia.edu) python-requests/2.34.2'}

In [9]:
root = 'https://api.congress.gov/v3'
endpoint = '/member'
params = {'format': 'json',
          'currentMember': True,
          'api_key': congresskey}
r = requests.get(root + endpoint, params=params, headers=headers)
r

### Step 2.

In [10]:
myjson = r.json()
myjson

{'members': [{'bioguideId': 'W000832',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
   'district': 14,
   'name': 'Wahab, Aisha',
   'partyName': 'Democratic',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
  {'bioguideId': 'B001328',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
   'district': 13,
   'name': 'Blair, Everton',
   'partyName': 'Democratic',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
  {'bioguideId': 'G000607',
   'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
   'district': 1,
   'name': 'Gallagher, James',
   'partyName': 'Republican',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
  {'bioguideId': 'M001246',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
   'district': 11,
   'name': 'Mejia, Analilia',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
  {'bioguideId': 'F000485',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
   'district': 14,
   'name': 'Fuller, Clay',
   'partyName': 'Republican',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
  {'bioguideId': 'M001245',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
   'district': 18,
   'name': 'Menefee, Christian D.',
   'partyName': 'Democratic',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
  {'bioguideId': 'V000139',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
   'district': 7,
   'name': 'Van Epps, Matt',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
  {'bioguideId': 'P000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
   'district': 1,
   'name': 'Patronis, Jimmy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
  {'bioguideId': 'F000484',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
   'district': 6,
   'name': 'Fine, Randy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
  {'bioguideId': 'V000138',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
   'district': 7,
   'name': 'Vindman, Eugene Simon',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
  {'bioguideId': 'T000490',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
   'district': 2,
   'name': 'Taylor, David J.',
   'partyName': 'Republican',
   'state': 'Ohio',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
  {'bioguideId': 'S001230',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
   'district': 10,
   'name': 'Subramanyam, Suhas',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
  {'bioguideId': 'S001229',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
   'district': 6,
   'name': 'Shreve, Jefferson',
   'partyName': 'Republican',
   'state': 'Indiana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
  {'bioguideId': 'S001228',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
   'district': 2,
   'name': 'Schmidt, Derek',
   'partyName': 'Republican',
   'state': 'Kansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
  {'bioguideId': 'R000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
   'district': 19,
   'name': 'Riley, Josh',
   'partyName': 'Democratic',
   'state': 'New York',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
  {'bioguideId': 'P000621',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
   'district': 9,
   'name': 'Pou, Nellie',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
  {'bioguideId': 'O000176',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
   'district': 2,
   'name': 'Olszewski, Johnny',
   'partyName': 'Democratic',
   'state': 'Maryland',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
  {'bioguideId': 'M001240',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
   'district': 6,
   'name': 'McDowell, Addison P.',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001240?format=json'},
  {'bioguideId': 'M001239',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
   'district': 5,
   'name': 'McGuire, John J.',
   'partyName': 'Republican',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001239?format=json'},
  {'bioguideId': 'M001238',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744b460b34857ecc909143_200.jpg'},
   'name': 'McBride, Sarah',
   'partyName': 'Democratic',
   'state': 'Delaware',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-24T07:40:27Z',
   'url': 'https://api.congress.gov/v3/member/M001238?format=json'}],
 'pagination': {'count': 539,
  'next': 'https://api.congress.gov/v3/member?currentMember=True&offset=20&limit=20&format=json'},
 'request': {'contentType': 'application/json', 'format': 'json'}}

In [11]:
myjson.keys()

dict_keys(['members', 'pagination', 'request'])

In [12]:
myjson['members'] # going down memebrs branch in a json dict

[{'bioguideId': 'W000832',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
  'district': 14,
  'name': 'Wahab, Aisha',
  'partyName': 'Democratic',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
 {'bioguideId': 'B001328',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
  'district': 13,
  'name': 'Blair, Everton',
  'partyName': 'Democratic',
  'state': 'Georgia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
 {'bioguideId': 'G000607',
  'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
  'district': 1,
  'name': 'Gallagher, James',
  'partyName': 'Republican',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
 {'bioguideId': 'M001246',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
  'district': 11,
  'name': 'Mejia, Analilia',
  'partyName': 'Democratic',
  'state': 'New Jersey',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
 {'bioguideId': 'F000485',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
  'district': 14,
  'name': 'Fuller, Clay',
  'partyName': 'Republican',
  'state': 'Georgia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
 {'bioguideId': 'M001245',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
  'district': 18,
  'name': 'Menefee, Christian D.',
  'partyName': 'Democratic',
  'state': 'Texas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
 {'bioguideId': 'V000139',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
  'district': 7,
  'name': 'Van Epps, Matt',
  'partyName': 'Republican',
  'state': 'Tennessee',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
 {'bioguideId': 'P000622',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
  'district': 1,
  'name': 'Patronis, Jimmy',
  'partyName': 'Republican',
  'state': 'Florida',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
 {'bioguideId': 'F000484',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
  'district': 6,
  'name': 'Fine, Randy',
  'partyName': 'Republican',
  'state': 'Florida',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
 {'bioguideId': 'V000138',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
  'district': 7,
  'name': 'Vindman, Eugene Simon',
  'partyName': 'Democratic',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
 {'bioguideId': 'T000490',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
  'district': 2,
  'name': 'Taylor, David J.',
  'partyName': 'Republican',
  'state': 'Ohio',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
 {'bioguideId': 'S001230',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
  'district': 10,
  'name': 'Subramanyam, Suhas',
  'partyName': 'Democratic',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
 {'bioguideId': 'S001229',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
  'district': 6,
  'name': 'Shreve, Jefferson',
  'partyName': 'Republican',
  'state': 'Indiana',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
 {'bioguideId': 'S001228',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
  'district': 2,
  'name': 'Schmidt, Derek',
  'partyName': 'Republican',
  'state': 'Kansas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
 {'bioguideId': 'R000622',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
  'district': 19,
  'name': 'Riley, Josh',
  'partyName': 'Democratic',
  'state': 'New York',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
 {'bioguideId': 'P000621',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
  'district': 9,
  'name': 'Pou, Nellie',
  'partyName': 'Democratic',
  'state': 'New Jersey',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
 {'bioguideId': 'O000176',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
  'district': 2,
  'name': 'Olszewski, Johnny',
  'partyName': 'Democratic',
  'state': 'Maryland',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
 {'bioguideId': 'M001240',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
  'district': 6,
  'name': 'McDowell, Addison P.',
  'partyName': 'Republican',
  'state': 'North Carolina',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001240?format=json'},
 {'bioguideId': 'M001239',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
  'district': 5,
  'name': 'McGuire, John J.',
  'partyName': 'Republican',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001239?format=json'},
 {'bioguideId': 'M001238',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744b460b34857ecc909143_200.jpg'},
  'name': 'McBride, Sarah',
  'partyName': 'Democratic',
  'state': 'Delaware',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001238?format=json'}]

In [13]:
len(myjson['members'])

20

In [14]:
myjson['members'][0]

{'bioguideId': 'W000832',
 'depiction': {'attribution': 'Image courtesy of the Member',
  'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
 'district': 14,
 'name': 'Wahab, Aisha',
 'partyName': 'Democratic',
 'state': 'California',
 'terms': {'item': [{'chamber': 'House of Representatives',
    'startYear': 2026}]},
 'updateDate': '2026-09-24T07:40:27Z',
 'url': 'https://api.congress.gov/v3/member/W000832?format=json'}

In [15]:
myjson['members'][0]['terms']

{'item': [{'chamber': 'House of Representatives', 'startYear': 2026}]}

In [16]:
myjson['members'][0]['terms']['item']

[{'chamber': 'House of Representatives', 'startYear': 2026}]

In [17]:
myjson['members'][0]['terms']['item'][0]

{'chamber': 'House of Representatives', 'startYear': 2026}

In [18]:
myjson['members'][0]['terms']['item'][0]['chamber']

'House of Representatives'

Record path -- somehwere in the JSON is a list where each item is one row of the dataframe you want to build. The record path is a sequence of keys to call to arrive at this list

In this case the record path is: just memerbs

In [19]:
congress_df = pd.json_normalize(myjson, record_path=['members'])
congress_df

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14.0,"Wahab, Aisha",Democratic,California,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13.0,"Blair, Everton",Democratic,Georgia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1.0,"Gallagher, James",Republican,California,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11.0,"Mejia, Analilia",Democratic,New Jersey,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14.0,"Fuller, Clay",Republican,Georgia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
5,M001245,18.0,"Menefee, Christian D.",Democratic,Texas,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/M001245?for...,Image courtesy of the Member,https://www.congress.gov/img/member/698206b2eb...,"[{'chamber': 'House of Representatives', 'star..."
6,V000139,7.0,"Van Epps, Matt",Republican,Tennessee,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/V000139?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6931b7d5f4...,"[{'chamber': 'House of Representatives', 'star..."
7,P000622,1.0,"Patronis, Jimmy",Republican,Florida,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/P000622?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67efdb991b...,"[{'chamber': 'House of Representatives', 'star..."
8,F000484,6.0,"Fine, Randy",Republican,Florida,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/F000484?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67efda8c1b...,"[{'chamber': 'House of Representatives', 'star..."
9,V000138,7.0,"Vindman, Eugene Simon",Democratic,Virginia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/V000138?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6774617a0b...,"[{'chamber': 'House of Representatives', 'star..."
10,T000490,2.0,"Taylor, David J.",Republican,Ohio,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/T000490?for...,Image courtesy of the Member,https://www.congress.gov/img/member/677460190b...,"[{'chamber': 'House of Representatives', 'star..."
11,S001230,10.0,"Subramanyam, Suhas",Democratic,Virginia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/S001230?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6797be8bc7...,"[{'chamber': 'House of Representatives', 'star..."
12,S001229,6.0,"Shreve, Jefferson",Republican,Indiana,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/S001229?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745f0e0b...,"[{'chamber': 'House of Representatives', 'star..."
13,S001228,2.0,"Schmidt, Derek",Republican,Kansas,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/S001228?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745ec50b...,"[{'chamber': 'House of Representatives', 'star..."
14,R000622,19.0,"Riley, Josh",Democratic,New York,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/R000622?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745e360b...,"[{'chamber': 'House of Representatives', 'star..."
15,P000621,9.0,"Pou, Nellie",Democratic,New Jersey,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/P000621?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745d3b0b...,"[{'chamber': 'House of Representatives', 'star..."
16,O000176,2.0,"Olszewski, Johnny",Democratic,Maryland,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/O000176?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a3974507d...,"[{'chamber': 'House of Representatives', 'star..."
17,M001240,6.0,"McDowell, Addison P.",Republican,North Carolina,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/M001240?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67744e930b...,"[{'chamber': 'House of Representatives', 'star..."
18,M001239,5.0,"McGuire, John J.",Republican,Virginia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/M001239?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67744ba20b...,"[{'chamber': 'House of Representatives', 'star..."
19,M001238,NaN,"McBride, Sarah",Democratic,Delaware,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/M001238?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67744b460b...,"[{'chamber': 'House of Representatives', 'star..."

### Step 3.

In [20]:
# we see that teh default limit is 20 (20 congress people) but we want the max 250 congress people
params['limit'] = '250'

In [21]:
r = requests.get(root + endpoint, params=params, headers=headers)
myjson = r.json()
congress_df = pd.json_normalize(myjson, record_path=['members'])

pd.set_option('display.max_rows', 10)
congress_df

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14.0,"Wahab, Aisha",Democratic,California,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13.0,"Blair, Everton",Democratic,Georgia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1.0,"Gallagher, James",Republican,California,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11.0,"Mejia, Analilia",Democratic,New Jersey,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14.0,"Fuller, Clay",Republican,Georgia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
...,...,...,...,...,...,...,...,...,...,...
245,V000133,2.0,"Van Drew, Jefferson",Republican,New Jersey,2026-09-24T07:40:24Z,https://api.congress.gov/v3/member/V000133?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67c0c39d53...,"[{'chamber': 'House of Representatives', 'star..."
246,C001119,2.0,"Craig, Angie",Democratic,Minnesota,2026-09-24T07:40:24Z,https://api.congress.gov/v3/member/C001119?for...,Image courtesy of the Member,https://www.congress.gov/img/member/c001119_20...,"[{'chamber': 'House of Representatives', 'star..."
247,G000586,4.0,"García, Jesús G. ""Chuy""",Democratic,Illinois,2026-09-24T07:40:24Z,https://api.congress.gov/v3/member/G000586?for...,Image courtesy of the Member,https://www.congress.gov/img/member/g000586_20...,"[{'chamber': 'House of Representatives', 'star..."
248,K000376,16.0,"Kelly, Mike",Republican,Pennsylvania,2026-09-24T07:40:24Z,https://api.congress.gov/v3/member/K000376?for...,Image courtesy of the Member,https://www.congress.gov/img/member/k000376_20...,"[{'chamber': 'House of Representatives', 'star..."
249,T000467,15.0,"Thompson, Glenn",Republican,Pennsylvania,2026-09-24T07:40:24Z,https://api.congress.gov/v3/member/T000467?for...,Congressional Pictorial Directory,https://www.congress.gov/img/member/115_rp_pa_...,"[{'chamber': 'House of Representatives', 'star..."

In [22]:
params['offset'] = '500'
r = requests.get(root + endpoint, params=params, headers=headers)
myjson = r.json()
congress_df = pd.json_normalize(myjson, record_path=['members'])
congress_df

,bioguideId,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,H001104,"Husted, Jon",Republican,Ohio,2026-03-08T10:31:32Z,https://api.congress.gov/v3/member/H001104?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/67f0316b1b...,"[{'chamber': 'Senate', 'startYear': 2025}]"
1,H001061,"Hoeven, John",Republican,North Dakota,2026-03-08T10:31:30Z,https://api.congress.gov/v3/member/H001061?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/h001061_20...,"[{'chamber': 'Senate', 'startYear': 2011}]"
2,H001042,"Hirono, Mazie K.",Democratic,Hawaii,2026-03-08T10:31:28Z,https://api.congress.gov/v3/member/H001042?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/h001042_20...,"[{'chamber': 'House of Representatives', 'endY..."
3,H000273,"Hickenlooper, John W.",Democratic,Colorado,2026-03-08T10:31:27Z,https://api.congress.gov/v3/member/H000273?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/h000273_20...,"[{'chamber': 'Senate', 'startYear': 2021}]"
4,H001046,"Heinrich, Martin",Democratic,New Mexico,2026-03-08T10:31:25Z,https://api.congress.gov/v3/member/H001046?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/h001046_20...,"[{'chamber': 'House of Representatives', 'endY..."
...,...,...,...,...,...,...,...,...,...
34,B001267,"Bennet, Michael F.",Democratic,Colorado,2026-03-08T10:30:30Z,https://api.congress.gov/v3/member/B001267?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001267_20...,"[{'chamber': 'Senate', 'startYear': 2009}]"
35,B001261,"Barrasso, John",Republican,Wyoming,2026-03-08T10:30:29Z,https://api.congress.gov/v3/member/B001261?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001261_20...,"[{'chamber': 'Senate', 'startYear': 2007}]"
36,B001299,"Banks, Jim",Republican,Indiana,2026-03-08T10:30:27Z,https://api.congress.gov/v3/member/B001299?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/677d83cbfd...,"[{'chamber': 'House of Representatives', 'endY..."
37,B001230,"Baldwin, Tammy",Democratic,Wisconsin,2026-03-08T10:30:26Z,https://api.congress.gov/v3/member/B001230?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001230_20...,"[{'chamber': 'House of Representatives', 'endY..."
38,A000382,"Alsobrooks, Angela D.",Democratic,Maryland,2026-03-08T10:30:24Z,https://api.congress.gov/v3/member/A000382?for...,NaN,https://www.congress.gov/img/member/67acdbbf04...,"[{'chamber': 'Senate', 'startYear': 2025}]"

In [23]:
i = 0 
still_members = True
congress_json = []
while still_members:
    print(i)
    params['offset'] = i
    r = requests.get(root + endpoint, params=params, headers=headers)
    myjson = r.json()
    still_members = len(myjson['members']) > 0
    congress_json.extend(myjson['members'])
    i = i + 250

0
250
500
750

we need a mechanism to page through the conrgess members which is conducted in the while loop.

In [24]:
congress_json

[{'bioguideId': 'W000832',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
  'district': 14,
  'name': 'Wahab, Aisha',
  'partyName': 'Democratic',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
 {'bioguideId': 'B001328',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
  'district': 13,
  'name': 'Blair, Everton',
  'partyName': 'Democratic',
  'state': 'Georgia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
 {'bioguideId': 'G000607',
  'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
  'district': 1,
  'name': 'Gallagher, James',
  'partyName': 'Republican',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
 {'bioguideId': 'M001246',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
  'district': 11,
  'name': 'Mejia, Analilia',
  'partyName': 'Democratic',
  'state': 'New Jersey',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
 {'bioguideId': 'F000485',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
  'district': 14,
  'name': 'Fuller, Clay',
  'partyName': 'Republican',
  'state': 'Georgia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
 {'bioguideId': 'M001245',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
  'district': 18,
  'name': 'Menefee, Christian D.',
  'partyName': 'Democratic',
  'state': 'Texas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2026}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
 {'bioguideId': 'V000139',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
  'district': 7,
  'name': 'Van Epps, Matt',
  'partyName': 'Republican',
  'state': 'Tennessee',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
 {'bioguideId': 'P000622',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
  'district': 1,
  'name': 'Patronis, Jimmy',
  'partyName': 'Republican',
  'state': 'Florida',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
 {'bioguideId': 'F000484',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
  'district': 6,
  'name': 'Fine, Randy',
  'partyName': 'Republican',
  'state': 'Florida',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
 {'bioguideId': 'V000138',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
  'district': 7,
  'name': 'Vindman, Eugene Simon',
  'partyName': 'Democratic',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
 {'bioguideId': 'T000490',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
  'district': 2,
  'name': 'Taylor, David J.',
  'partyName': 'Republican',
  'state': 'Ohio',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
 {'bioguideId': 'S001230',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
  'district': 10,
  'name': 'Subramanyam, Suhas',
  'partyName': 'Democratic',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
 {'bioguideId': 'S001229',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
  'district': 6,
  'name': 'Shreve, Jefferson',
  'partyName': 'Republican',
  'state': 'Indiana',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
 {'bioguideId': 'S001228',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
  'district': 2,
  'name': 'Schmidt, Derek',
  'partyName': 'Republican',
  'state': 'Kansas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
 {'bioguideId': 'R000622',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
  'district': 19,
  'name': 'Riley, Josh',
  'partyName': 'Democratic',
  'state': 'New York',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
 {'bioguideId': 'P000621',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
  'district': 9,
  'name': 'Pou, Nellie',
  'partyName': 'Democratic',
  'state': 'New Jersey',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
 {'bioguideId': 'O000176',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
  'district': 2,
  'name': 'Olszewski, Johnny',
  'partyName': 'Democratic',
  'state': 'Maryland',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
 {'bioguideId': 'M001240',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
  'district': 6,
  'name': 'McDowell, Addison P.',
  'partyName': 'Republican',
  'state': 'North Carolina',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001240?format=json'},
 {'bioguideId': 'M001239',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
  'district': 5,
  'name': 'McGuire, John J.',
  'partyName': 'Republican',
  'state': 'Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001239?format=json'},
 {'bioguideId': 'M001238',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744b460b34857ecc909143_200.jpg'},
  'name': 'McBride, Sarah',
  'partyName': 'Democratic',
  'state': 'Delaware',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001238?format=json'},
 {'bioguideId': 'M001237',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/69d7f4ee7304cef7a0c977a8_200.jpg'},
  'district': 8,
  'name': 'McDonald Rivet, Kristen',
  'partyName': 'Democratic',
  'state': 'Michigan',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001237?format=json'},
 {'bioguideId': 'M001236',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744a540b34857ecc909137_200.jpg'},
  'district': 14,
  'name': 'Moore, Tim',
  'partyName': 'Republican',
  'state': 'North Carolina',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001236?format=json'},
 {'bioguideId': 'M001235',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677449fd0b34857ecc909131_200.jpg'},
  'district': 2,
  'name': 'Moore, Riley M.',
  'partyName': 'Republican',
  'state': 'West Virginia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001235?format=json'},
 {'bioguideId': 'M001233',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677448630b34857ecc909125_200.jpg'},
  'district': 8,
  'name': 'Messmer, Mark B.',
  'partyName': 'Republican',
  'state': 'Indiana',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001233?format=json'},
 {'bioguideId': 'M001232',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677446d80b34857ecc90911f_200.jpg'},
  'district': 6,
  'name': 'McClain Delaney, April',
  'partyName': 'Democratic',
  'state': 'Maryland',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001232?format=json'},
 {'bioguideId': 'M001231',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677446860b34857ecc909119_200.jpg'},
  'district': 22,
  'name': 'Mannion, John W.',
  'partyName': 'Democratic',
  'state': 'New York',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001231?format=json'},
 {'bioguideId': 'M001230',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677430a40b34857ecc909113_200.jpg'},
  'district': 7,
  'name': 'Mackenzie, Ryan',
  'partyName': 'Republican',
  'state': 'Pennsylvania',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/M001230?format=json'},
 {'bioguideId': 'L000606',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6774301b0b34857ecc909107_200.jpg'},
  'district': 16,
  'name': 'Latimer, George',
  'partyName': 'Democratic',
  'state': 'New York',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/L000606?format=json'},
 {'bioguideId': 'K000405',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67742fc60b34857ecc909101_200.jpg'},
  'district': 13,
  'name': 'Knott, Brad',
  'partyName': 'Republican',
  'state': 'North Carolina',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/K000405?format=json'},
 {'bioguideId': 'K000403',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67742e7c0b34857ecc9090f5_200.jpg'},
  'district': 3,
  'name': 'Kennedy, Mike',
  'partyName': 'Republican',
  'state': 'Utah',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/K000403?format=json'},
 {'bioguideId': 'J000311',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67742e330b34857ecc9090ef_200.jpg'},
  'district': 3,
  'name': 'Jack, Brian',
  'partyName': 'Republican',
  'state': 'Georgia',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/J000311?format=json'},
 {'bioguideId': 'J000310',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67742df60b34857ecc9090e9_200.jpg'},
  'district': 32,
  'name': 'Johnson, Julie',
  'partyName': 'Democratic',
  'state': 'Texas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/J000310?format=json'},
 {'bioguideId': 'H001103',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67742d980b34857ecc9090e3_200.jpg'},
  'name': 'Hernández, Pablo Jose',
  'partyName': 'Democratic',
  'state': 'Puerto Rico',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/H001103?format=json'},
 {'bioguideId': 'H001102',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67742d1b0b34857ecc9090dd_200.jpg'},
  'district': 8,
  'name': 'Harris, Mark',
  'partyName': 'Republican',
  'state': 'North Carolina',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/H001102?format=json'},
 {'bioguideId': 'H001101',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67742ca40b34857ecc9090d7_200.jpg'},
  'district': 10,
  'name': 'Harrigan, Pat',
  'partyName': 'Republican',
  'state': 'North Carolina',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/H001101?format=json'},
 {'bioguideId': 'H001099',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67742ab50b34857ecc9090cb_200.jpg'},
  'district': 8,
  'name': 'Haridopolos, Mike',
  'partyName': 'Republican',
  'state': 'Florida',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/H001099?format=json'},
 {'bioguideId': 'G000604',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/678ff62d66bf616cf1a7ce13_200.jpg'},
  'district': 2,
  'name': 'Goodlander, Maggie',
  'partyName': 'Democratic',
  'state': 'New Hampshire',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/G000604?format=json'},
 {'bioguideId': 'G000603',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677428ac0b34857ecc9090b3_200.jpg'},
  'district': 26,
  'name': 'Gill, Brandon',
  'partyName': 'Republican',
  'state': 'Texas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/G000603?format=json'},
 {'bioguideId': 'G000602',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677427de0b34857ecc9090ad_200.jpg'},
  'district': 4,
  'name': 'Gillen, Laura',
  'partyName': 'Democratic',
  'state': 'New York',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/G000602?format=json'},
 {'bioguideId': 'G000601',
  'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6774277d0b34857ecc9090a7_200.jpg'},
  'district': 12,
  'name': 'Goldman, Craig A.',
  'partyName': 'Republican',
  'state': 'Texas',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/G000601?format=json'},
 {'bioguideId': 'F000483',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6a0f0dcb69b12040cf77e337_200.jpg'},
  'district': 30,
  'name': 'Friedman, Laura',
  'partyName': 'Democratic',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/F000483?format=json'},
 {'bioguideId': 'F000482',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/677426c20b34857ecc90909b_200.jpg'},
  'name': 'Fedorchak, Julie',
  'partyName': 'Republican',
  'state': 'North Dakota',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2026-09-24T07:40:27Z',
  'url': 'https://api.congress.gov/v3/member/F000482?format=json'},
 {'bioguideId': 'F000481',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/68013eaa4e51529406f18e42_200.jpg'},
  'district': 2,
  'name': 'Figures, Shomari',
  'partyName': 'Democratic',

In [25]:
len(congress_json)

539

In [26]:
congress_df = pd.json_normalize(congress_json)

In [27]:
congress_df

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14.0,"Wahab, Aisha",Democratic,California,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13.0,"Blair, Everton",Democratic,Georgia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1.0,"Gallagher, James",Republican,California,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11.0,"Mejia, Analilia",Democratic,New Jersey,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14.0,"Fuller, Clay",Republican,Georgia,2026-09-24T07:40:27Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
...,...,...,...,...,...,...,...,...,...,...
534,B001267,NaN,"Bennet, Michael F.",Democratic,Colorado,2026-03-08T10:30:30Z,https://api.congress.gov/v3/member/B001267?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001267_20...,"[{'chamber': 'Senate', 'startYear': 2009}]"
535,B001261,NaN,"Barrasso, John",Republican,Wyoming,2026-03-08T10:30:29Z,https://api.congress.gov/v3/member/B001261?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001261_20...,"[{'chamber': 'Senate', 'startYear': 2007}]"
536,B001299,NaN,"Banks, Jim",Republican,Indiana,2026-03-08T10:30:27Z,https://api.congress.gov/v3/member/B001299?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/677d83cbfd...,"[{'chamber': 'House of Representatives', 'endY..."
537,B001230,NaN,"Baldwin, Tammy",Democratic,Wisconsin,2026-03-08T10:30:26Z,https://api.congress.gov/v3/member/B001230?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001230_20...,"[{'chamber': 'House of Representatives', 'endY..."
538,A000382,NaN,"Alsobrooks, Angela D.",Democratic,Maryland,2026-03-08T10:30:24Z,https://api.congress.gov/v3/member/A000382?for...,NaN,https://www.congress.gov/img/member/67acdbbf04...,"[{'chamber': 'Senate', 'startYear': 2025}]"

In [29]:
# we can use the combo of district number and state to uniquely identify a congressman
# query is used conduct querying and filtering
# the & symbol is the `and` operator for the query pandas package
# and lowercase also works
mcguire_df = congress_df.query("state == 'Virginia' & district == 5")

In [36]:
bioguideId = mcguire_df.reset_index()['bioguideId'][0]
bioguideId

'M001239'

In [38]:
endpoint = f'/member/{bioguideId}'
endpoint

'/member/M001239'

In [39]:
params = {'api_key': congresskey,
          'formet': 'json'}

r = requests.get(root + endpoint, headers=headers, params=params)
r

In [41]:
r.json()

{'member': {'addressInformation': {'city': 'Washington',
   'district': 'DC',
   'officeAddress': '1013 Longworth House Office Building',
   'phoneNumber': '(202) 225-4711',
   'zipCode': 20515},
  'bioguideId': 'M001239',
  'birthYear': '1968',
  'cosponsoredLegislation': {'count': 310,
   'url': 'https://api.congress.gov/v3/member/M001239/cosponsored-legislation'},
  'currentMember': True,
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
  'directOrderName': 'John J. McGuire III',
  'district': 5,
  'firstName': 'John',
  'honorificName': 'Mr.',
  'invertedOrderName': 'McGuire, John J.',
  'lastName': 'McGuire',
  'middleName': 'J.',
  'officialWebsiteUrl': 'https://mcguire.house.gov/',
  'partyHistory': [{'partyAbbreviation': 'R',
    'partyName': 'Republican',
    'startYear': 2025}],
  'previousNames': [{'directOrderName': 'John McGuire',
    'endDate': '2025-01-10T17:36:18Z',
    'firstName': 'John',
    'honorificName': 'Mr.',
    'invertedOrderName': 'McGuire, John',
    'lastName': 'McGuire',
    'middleName': 'J.',
    'startDate': '2025-01-03T17:00:00Z'},
   {'directOrderName': 'John McGuire',
    'endDate': '2025-01-17T04:59:59Z',
    'firstName': 'John',
    'honorificName': 'Mr.',
    'invertedOrderName': 'McGuire, John',
    'lastName': 'McGuire',
    'middleName': 'J.',
    'startDate': '2025-01-10T17:36:19Z'},
   {'directOrderName': 'John McGuire',
    'endDate': '2025-04-28T13:04:26Z',
    'firstName': 'John',
    'honorificName': 'Mr.',
    'invertedOrderName': 'McGuire, John',
    'lastName': 'McGuire',
    'middleName': 'J.',
    'startDate': '2025-01-17T05:00:00Z'},
   {'directOrderName': 'John J. McGuire III',
    'firstName': 'John',
    'honorificName': 'Mr.',
    'invertedOrderName': 'McGuire, John J.',
    'lastName': 'McGuire',
    'middleName': 'J.',
    'startDate': '2025-04-28T13:04:27Z'}],
  'sponsoredLegislation': {'count': 22,
   'url': 'https://api.congress.gov/v3/member/M001239/sponsored-legislation'},
  'state': 'Virginia',
  'suffixName': 'III',
  'terms': [{'chamber': 'House of Representatives',
    'congress': 119,
    'district': 5,
    'memberType': 'Representative',
    'startYear': 2025,
    'stateCode': 'VA',
    'stateName': 'Virginia'}],
  'updateDate': '2026-09-24T07:40:27Z'},
 'request': {'bioguideId': 'm001239',
  'contentType': 'application/json',
  'format': 'json'}}

In [43]:
endpoint = f'/member/{bioguideId}/sponsored-legislation'

params = {'api_key': congresskey,
          'formet': 'json'}

r = requests.get(root + endpoint, headers=headers, params=params)
r

In [44]:
r.json()

{'pagination': {'count': 22,
  'next': 'https://api.congress.gov/v3/member/M001239/sponsored-legislation?formet=json&offset=20&limit=20&format=json'},
 'request': {'bioguideId': 'm001239',
  'contentType': 'application/json',
  'format': 'json'},
 'sponsoredLegislation': [{'congress': 119,
   'introducedDate': '2026-05-15',
   'latestAction': {'actionDate': '2026-05-15',
    'text': 'Referred to the House Committee on the Judiciary.'},
   'number': '8843',
   'policyArea': {'name': 'Crime and Law Enforcement'},
   'title': 'FAFO Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/8843?format=json'},
  {'congress': 119,
   'introducedDate': '2025-07-22',
   'latestAction': {'actionDate': '2025-07-22',
    'text': 'Referred to the House Committee on Energy and Commerce.'},
   'number': '4603',
   'policyArea': {'name': 'Energy'},
   'title': 'FAIR Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/4603?format=json'},
  {'congress': 119,
   'introducedDate': '2026-07-16',
   'latestAction': {'actionDate': '2026-07-16',
    'text': 'Referred to the House Committee on the Judiciary.'},
   'number': '9756',
   'policyArea': {'name': 'Health'},
   'title': 'MAT Act of 2026',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/9756?format=json'},
  {'congress': 119,
   'introducedDate': '2026-07-09',
   'latestAction': {'actionDate': '2026-07-09',
    'text': 'Referred to the House Committee on the Judiciary.'},
   'number': '9633',
   'policyArea': {'name': 'Immigration'},
   'title': 'Birthright Citizenship Clarification Act of 2026',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/9633?format=json'},
  {'congress': 119,
   'introducedDate': '2026-06-29',
   'latestAction': {'actionDate': '2026-06-29',
    'text': 'Referred to the House Committee on the Judiciary.'},
   'number': '9522',
   'policyArea': {'name': 'Congress'},
   'title': 'National Patriot Day Remembrance Flag Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/9522?format=json'},
  {'congress': 119,
   'introducedDate': '2026-03-16',
   'latestAction': {'actionDate': '2026-03-16',
    'text': 'Referred to the House Committee on the Judiciary.'},
   'number': '7935',
   'policyArea': {'name': 'Crime and Law Enforcement'},
   'title': 'Shall Not Be Infringed Act of 2026',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/7935?format=json'},
  {'congress': 119,
   'introducedDate': '2026-02-10',
   'latestAction': {'actionDate': '2026-02-10',
    'text': 'Referred to the House Committee on Education and Workforce.'},
   'number': '1053',
   'policyArea': {'name': 'Education'},
   'title': 'Honoring Sweet Briar College on the 125th anniversary of its founding.',
   'type': 'HRES',
   'url': 'https://api.congress.gov/v3/bill/119/hres/1053?format=json'},
  {'congress': 119,
   'introducedDate': '2026-02-04',
   'latestAction': {'actionDate': '2026-02-04',
    'text': 'Referred to the House Committee on the Judiciary.'},
   'number': '7368',
   'policyArea': {'name': 'Sports and Recreation'},
   'title': 'Riley Gaines Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/7368?format=json'},
  {'congress': 119,
   'introducedDate': '2026-01-30',
   'latestAction': {'actionDate': '2026-01-30',
    'text': 'Referred to the House Committee on the Judiciary.'},
   'number': '1024',
   'policyArea': {'name': 'Crime and Law Enforcement'},
   'title': 'Expressing support for the designation of January 2026 as "National Human Trafficking Prevention Month".',
   'type': 'HRES',
   'url': 'https://api.congress.gov/v3/bill/119/hres/1024?format=json'},
  {'congress': 119,
   'introducedDate': '2026-01-21',
   'latestAction': {'actionDate': '2026-01-21',
    'text': 'Referred to the House Committee on Ways and Means.'},
   'number': '7185',
   'policyArea': {'name': 'Taxation'},
   'title': 'Home Savings Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/7185?format=json'},
  {'congress': 119,
   'introducedDate': '2026-01-14',
   'latestAction': {'actionDate': '2026-01-14',
    'text': 'Referred to the House Committee on Ways and Means.'},
   'number': '7051',
   'policyArea': {'name': 'Taxation'},
   'title': 'American Dream Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/7051?format=json'},
  {'amendmentNumber': '120',
   'congress': 119,
   'introducedDate': '2025-12-10',
   'latestAction': {'actionDate': '2025-12-10',
    'actionTime': '19:28:34',
    'text': 'On agreeing to the McGuire amendment (A003) Agreed to by voice vote.'},
   'type': None,
   'url': 'https://api.congress.gov/v3/amendment/119/hamdt/120?format=json'},
  {'congress': 119,
   'introducedDate': '2025-12-02',
   'latestAction': {'actionDate': '2026-09-17',
    'text': 'Placed on Senate Legislative Calendar under General Orders. Calendar No. 664.'},
   'number': '6365',
   'policyArea': {'name': 'Public Lands and Natural Resources'},
   'title': 'Wintergreen Emergency Egress Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/6365?format=json'},
  {'congress': 119,
   'introducedDate': '2025-11-04',
   'latestAction': {'actionDate': '2025-11-04',
    'text': 'Referred to the House Committee on Education and Workforce.'},
   'number': '859',
   'policyArea': {'name': 'Education'},
   'title': 'Honoring Hampden-Sydney College on the 250th anniversary of its founding.',
   'type': 'HRES',
   'url': 'https://api.congress.gov/v3/bill/119/hres/859?format=json'},
  {'congress': 119,
   'introducedDate': '2025-09-26',
   'latestAction': {'actionDate': '2025-09-26',
    'text': 'Referred to the House Committee on Ways and Means.'},
   'number': '5595',
   'policyArea': {'name': 'Taxation'},
   'title': 'Requiring Excise for Migrant Income Transfers Act” or the “REMIT Act.',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/5595?format=json'},
  {'congress': 119,
   'introducedDate': '2025-09-19',
   'latestAction': {'actionDate': '2025-09-19',
    'text': 'Referred to the House Committee on Armed Services.'},
   'number': '5522',
   'policyArea': {'name': 'Armed Forces and National Security'},
   'title': 'Peace Through Strength Act of 2025',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/5522?format=json'},
  {'congress': 119,
   'introducedDate': '2025-09-09',
   'latestAction': {'actionDate': '2025-09-10',
    'text': 'Referred to the Subcommittee on Border Security and Enforcement.'},
   'number': '5218',
   'policyArea': {'name': 'Immigration'},
   'title': 'Border Wall Status Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/5218?format=json'},
  {'congress': 119,
   'introducedDate': '2025-09-03',
   'latestAction': {'actionDate': '2026-06-16',
    'text': 'Read twice. Placed on Senate Legislative Calendar under General Orders. Calendar No. 437.'},
   'number': '5103',
   'policyArea': {'name': 'Public Lands and Natural Resources'},
   'title': 'Make the District of Columbia Safe and Beautiful Act of 2025',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/5103?format=json'},
  {'congress': 119,
   'introducedDate': '2025-05-29',
   'latestAction': {'actionDate': '2025-06-12',
    'text': 'Subcommittee Hearings Held'},
   'number': '3643',
   'policyArea': {'name': 'Armed Forces and National Security'},
   'title': 'VA Data Transparency and Trust Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/3643?format=json'},
  {'congress': 119,
   'introducedDate': '2025-05-17',
   'latestAction': {'actionDate': '2025-05-18',
    'text': 'Referred to the Subcommittee on Aviation.'},
   'number': '3478',
   'policyArea': {'name': 'Crime and Law Enforcement'},
   'title': 'Manned Aircraft Clarification Act',
   'type': 'HR',
   'url': 'https://api.congress.gov/v3/bill/119/hr/3478?format=json'}]}

In [45]:
mcguire_bills_df = pd.json_normalize(r.json(), record_path=['sponsoredLegislation'])
mcguire_bills_df

,congress,introducedDate,number,title,type,url,latestAction.actionDate,latestAction.text,policyArea.name,amendmentNumber,latestAction.actionTime
0,119,2026-05-15,8843,FAFO Act,HR,https://api.congress.gov/v3/bill/119/hr/8843?f...,2026-05-15,Referred to the House Committee on the Judiciary.,Crime and Law Enforcement,NaN,NaN
1,119,2025-07-22,4603,FAIR Act,HR,https://api.congress.gov/v3/bill/119/hr/4603?f...,2025-07-22,Referred to the House Committee on Energy and ...,Energy,NaN,NaN
2,119,2026-07-16,9756,MAT Act of 2026,HR,https://api.congress.gov/v3/bill/119/hr/9756?f...,2026-07-16,Referred to the House Committee on the Judiciary.,Health,NaN,NaN
3,119,2026-07-09,9633,Birthright Citizenship Clarification Act of 2026,HR,https://api.congress.gov/v3/bill/119/hr/9633?f...,2026-07-09,Referred to the House Committee on the Judiciary.,Immigration,NaN,NaN
4,119,2026-06-29,9522,National Patriot Day Remembrance Flag Act,HR,https://api.congress.gov/v3/bill/119/hr/9522?f...,2026-06-29,Referred to the House Committee on the Judiciary.,Congress,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
15,119,2025-09-19,5522,Peace Through Strength Act of 2025,HR,https://api.congress.gov/v3/bill/119/hr/5522?f...,2025-09-19,Referred to the House Committee on Armed Servi...,Armed Forces and National Security,NaN,NaN
16,119,2025-09-09,5218,Border Wall Status Act,HR,https://api.congress.gov/v3/bill/119/hr/5218?f...,2025-09-10,Referred to the Subcommittee on Border Securit...,Immigration,NaN,NaN
17,119,2025-09-03,5103,Make the District of Columbia Safe and Beautif...,HR,https://api.congress.gov/v3/bill/119/hr/5103?f...,2026-06-16,Read twice. Placed on Senate Legislative Calen...,Public Lands and Natural Resources,NaN,NaN
18,119,2025-05-29,3643,VA Data Transparency and Trust Act,HR,https://api.congress.gov/v3/bill/119/hr/3643?f...,2025-06-12,Subcommittee Hearings Held,Armed Forces and National Security,NaN,NaN
19,119,2025-05-17,3478,Manned Aircraft Clarification Act,HR,https://api.congress.gov/v3/bill/119/hr/3478?f...,2025-05-18,Referred to the Subcommittee on Aviation.,Crime and Law Enforcement,NaN,NaN

In [47]:
pd.set_option('display.max_row', 20)
mcguire_bills_df['title']

0                                              FAFO Act
1                                              FAIR Act
2                                       MAT Act of 2026
3      Birthright Citizenship Clarification Act of 2026
4             National Patriot Day Remembrance Flag Act
5                    Shall Not Be Infringed Act of 2026
6     Honoring Sweet Briar College on the 125th anni...
7                                      Riley Gaines Act
8     Expressing support for the designation of Janu...
9                                      Home Savings Act
10                                   American Dream Act
11                                                  NaN
12                     Wintergreen Emergency Egress Act
13    Honoring Hampden-Sydney College on the 250th a...
14    Requiring Excise for Migrant Income Transfers ...
15                   Peace Through Strength Act of 2025
16                               Border Wall Status Act
17    Make the District of Columbia Safe and Beautif...
18                   VA Data Transparency and Trust Act
19                    Manned Aircraft Clarification Act
Name: title, dtype: str

In [50]:
mcguire_bills_df['title'][11]

nan

In [53]:
mcguire_bills_df.loc[11]

congress                                                                 119
introducedDate                                                    2025-12-10
number                                                                   NaN
title                                                                    NaN
type                                                                     NaN
url                        https://api.congress.gov/v3/amendment/119/hamd...
latestAction.actionDate                                           2025-12-10
latestAction.text          On agreeing to the McGuire amendment (A003) Ag...
policyArea.name                                                          NaN
amendmentNumber                                                          120
latestAction.actionTime                                             19:28:34
Name: 11, dtype: object