In [9]:
import numpy as np
import pandas as pd

In [10]:
votes = pd.read_csv("https://voteview.com/static/data/out/votes/HS119_votes.csv")

In [11]:
votes.head(3).T

                0      1      2
congress      119    119    119
chamber     House  House  House
rollnumber      1      1      1
icpsr       14854  14863  14873
cast_code       1      1      6
prob         99.6   78.9  100.0

# Pandas Skills: Filter Columns

In [12]:
# index a dataframe then give it a list df[[]] where the list contains column names ['column1', 'column2', ...]
votes = votes[['chamber', 'rollnumber', 'icpsr', 'cast_code']] # keep columns

# or do this:
#votes = votes.drop(['congress', 'prob']) # drop columns

In [13]:
votes

       chamber  rollnumber  icpsr  cast_code
0        House           1  14854          1
1        House           1  14863          1
2        House           1  14873          6
3        House           1  15029          6
4        House           1  15433          6
...        ...         ...    ...        ...
383026  Senate         915  42506          1
383027  Senate         915  42507          1
383028  Senate         915  42508          1
383029  Senate         915  49308          6
383030  Senate         915  49703          1

[383031 rows x 4 columns]

In [14]:
data1 = [{'id': 1, 'x': 'a'}, {'id': 1, 'x': 'b'}, {'id': 1, 'x': 'c'}]
data2 = [{'id': 1, 'y': 'd'}, {'id': 1, 'y': 'e'}, {'id': 1, 'y': 'f'}]

In [15]:
data1

[{'id': 1, 'x': 'a'}, {'id': 1, 'x': 'b'}, {'id': 1, 'x': 'c'}]

In [16]:
data2

[{'id': 1, 'y': 'd'}, {'id': 1, 'y': 'e'}, {'id': 1, 'y': 'f'}]

In [17]:
meregedata = pd.merge(pd.DataFrame(data1), 
                      pd.DataFrame(data2), on='id')
meregedata # many to many merge

   id  x  y
0   1  a  d
1   1  a  e
2   1  a  f
3   1  b  d
4   1  b  e
5   1  b  f
6   1  c  d
7   1  c  e
8   1  c  f

# Pandas Skill: many-to-many joins (usually we don't want this! but here we do)

In [18]:
vote_compare = pd.merge(votes, votes, 
                         on = ['chamber', 'rollnumber']) # merge votes with itself on chamber and rollnumber
vote_compare # automatically specifies which icpsr and cast_code coems from the left side and the right side

          chamber  rollnumber  icpsr_x  cast_code_x  icpsr_y  cast_code_y
0           House           1    14854            1    14854            1
1           House           1    14854            1    14863            1
2           House           1    14854            1    14873            6
3           House           1    14854            1    15029            6
4           House           1    14854            1    15433            6
...           ...         ...      ...          ...      ...          ...
135162640  Senate         915    49703            1    42506            1
135162641  Senate         915    49703            1    42507            1
135162642  Senate         915    49703            1    42508            1
135162643  Senate         915    49703            1    49308            6
135162644  Senate         915    49703            1    49703            1

[135162645 rows x 6 columns]

# Pandas Skill: more dropping

In [19]:
vote_compare = vote_compare.drop(['chamber', 'rollnumber'], axis=1) # remove the chmaber and rollnumber columns since we dont need them anymore
vote_compare

           icpsr_x  cast_code_x  icpsr_y  cast_code_y
0            14854            1    14854            1
1            14854            1    14863            1
2            14854            1    14873            6
3            14854            1    15029            6
4            14854            1    15433            6
...            ...          ...      ...          ...
135162640    49703            1    42506            1
135162641    49703            1    42507            1
135162642    49703            1    42508            1
135162643    49703            1    49308            6
135162644    49703            1    49703            1

[135162645 rows x 4 columns]

# Pandas Skill: create new column

In [20]:
vote_compare['agree'] = vote_compare['cast_code_x'] == vote_compare['cast_code_y'] # create a new column 'agree' to indicate whether the cast codes match
vote_compare

           icpsr_x  cast_code_x  icpsr_y  cast_code_y  agree
0            14854            1    14854            1   True
1            14854            1    14863            1   True
2            14854            1    14873            6  False
3            14854            1    15029            6  False
4            14854            1    15433            6  False
...            ...          ...      ...          ...    ...
135162640    49703            1    42506            1   True
135162641    49703            1    42507            1   True
135162642    49703            1    42508            1   True
135162643    49703            1    49308            6  False
135162644    49703            1    49703            1   True

[135162645 rows x 5 columns]

In [21]:
vote_compare = vote_compare.drop(['cast_code_x', 'cast_code_y'], axis=1) # remove the cast_code columns since we dont need them anymore
vote_compare

           icpsr_x  icpsr_y  agree
0            14854    14854   True
1            14854    14863   True
2            14854    14873  False
3            14854    15029  False
4            14854    15433  False
...            ...      ...    ...
135162640    49703    42506   True
135162641    49703    42507   True
135162642    49703    42508   True
135162643    49703    49308  False
135162644    49703    49703   True

[135162645 rows x 3 columns]

# Pandas Skill: filter rows

In [22]:
vote_compare = vote_compare.query('icpsr_x != icpsr_y') # filter out rows where the icpsr values are the same
vote_compare

           icpsr_x  icpsr_y  agree
1            14854    14863   True
2            14854    14873  False
3            14854    15029  False
4            14854    15433  False
5            14854    15448  False
...            ...      ...    ...
135162639    49703    42505   True
135162640    49703    42506   True
135162641    49703    42507   True
135162642    49703    42508   True
135162643    49703    49308  False

[134779614 rows x 3 columns]

# Pandas Skill: rename columns

In [23]:
vote_compare = vote_compare.rename({'icpsr_x': 'icpsr', 
                                    'icpsr_y': 'comparison member'},
                                    axis=1)
vote_compare

           icpsr  comparison member  agree
1          14854              14863   True
2          14854              14873  False
3          14854              15029  False
4          14854              15433  False
5          14854              15448  False
...          ...                ...    ...
135162639  49703              42505   True
135162640  49703              42506   True
135162641  49703              42507   True
135162642  49703              42508   True
135162643  49703              49308  False

[134779614 rows x 3 columns]

# Pandas Skill: sorting

In [24]:
vote_compare = vote_compare.sort_values(['icpsr', 'comparison member'], ascending=True) # sort the dataframe by icpsr and comparison member columns in ascending order
vote_compare

           icpsr  comparison member  agree
125985887  14226              14435  False
125995688  14226              14435  False
126005292  14226              14435  False
126015093  14226              14435  False
126024894  14226              14435  False
...          ...                ...    ...
37045188   99912              91980   True
37232677   99912              91980   True
37420166   99912              91980   True
37794279   99912              91980   True
49294949   99912              91980   True

[134779614 rows x 3 columns]

# Pandas Skill: data aggregation

In [25]:
vote_compare = vote_compare.groupby(['icpsr', 'comparison member']).agg({'agree': 'mean'})
vote_compare

                            agree
icpsr comparison member
14226 14435              0.028415
      14858              0.077596
      14871              0.060109
      14921              0.798907
      15021              0.123497
...                           ...
99912 42505              1.000000
      42506              1.000000
      49308              0.000000
      49703              0.972414
      91980              0.933333

[215354 rows x 1 columns]

In [26]:
vote_compare = vote_compare.groupby(['icpsr', 'comparison member']).agg({'agree': 'mean'}).reset_index()
vote_compare

        icpsr  comparison member     agree
0       14226              14435  0.028415
1       14226              14858  0.077596
2       14226              14871  0.060109
3       14226              14921  0.798907
4       14226              15021  0.123497
...       ...                ...       ...
215349  99912              42505  1.000000
215350  99912              42506  1.000000
215351  99912              49308  0.000000
215352  99912              49703  0.972414
215353  99912              91980  0.933333

[215354 rows x 3 columns]

In [27]:
# user supplies for example 14226
user = 14226
vote_compare.query(f'icpsr == {user}').sort_values('agree', ascending=False).head(10)

     icpsr  comparison member     agree
103  14226              99912  1.000000
91   14226              42304  1.000000
57   14226              41102  1.000000
20   14226              21166  0.961749
49   14226              40707  0.958470
89   14226              42302  0.958470
72   14226              41505  0.957377
59   14226              41107  0.957377
65   14226              41302  0.955191
31   14226              21734  0.955191

In [28]:
vote_compare.query(f'icpsr == {user}').sort_values('agree', ascending=True).head(10)

     icpsr  comparison member     agree
0    14226              14435  0.028415
64   14226              41301  0.030601
37   14226              29147  0.031694
10   14226              20707  0.037158
8    14226              20330  0.046995
52   14226              40908  0.048087
2    14226              14871  0.060109
101  14226              49308  0.061202
29   14226              21706  0.062295
76   14226              41706  0.063388

In [33]:
import os
os.chdir('congress_transparency_class26')
from contrans import contrans
ct = contrans()

In [34]:
ct.get_vote_similarity_data()

In [35]:
vote_compare = pd.read_parquet("data/raw/vote_compare.parquet")
vote_compare.head()

                    bioname                    comparison_member     agree
0  GRASSLEY, Charles Ernest                  MARKEY, Edward John  0.028415
1  GRASSLEY, Charles Ernest       SCHUMER, Charles Ellis (Chuck)  0.077596
2  GRASSLEY, Charles Ernest                    WYDEN, Ronald Lee  0.060109
3  GRASSLEY, Charles Ernest  MCCONNELL, Addison Mitchell (Mitch)  0.798907
4  GRASSLEY, Charles Ernest               DURBIN, Richard Joseph  0.123497

In [32]:
os.getcwd()

'c:\\Users\\samia\\OneDrive\\Desktop\\DS-6600 Data Engineering Data Management and Visualization'